#define ppppppppppppppppppppppppppppppppppppppppppp 'f'
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppp '5'
#define pppppppppppppppppppppppppppppppppppppppp 'g'
#define pppp &&
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 13
#define pppppppppppppppppppppppppp 10
#define ppppppppppppppppppppppp 19
#define pppppppppppppppppppppppppppppppppppppppppppppppp scanf
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppppp '5'
#define ppppppppppppppppppppppppp '\0'
#define ppp int
#define pppppppppppppppppppppppppppppppppppp printf
#define ppppppppppppppppppppppppppppppppppppppppppppppppp 6
#define ppppppppppppp '4'
#define ppppppppppppppppp ;
#define pppppppp '0'
#define pppppppppppp 4
#define pppppppppppppppppppppppppppppppppppppp pppppppppppppppppppppppp
#define pppppppppppppppppppp ppppppppppppp
#define pppppppppppppppppppppppppppppppppppppppppppp =
#define pppppppppppppppp 8
#define pppppppppppppppppppppppppppppppppp 18
#define pp p
#define ppppppppppppppp 'l'
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 12
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp '2'
#define ppppppp 'g'
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 16
#define ppppppppppppppppppppppppppppppppppppppppppppp '}'
#define ppppppppppppppppppp main()
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 9
#define pppppppppppppppppppppppp flag
#define pppppp 'a'
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 17
#define ppppppppp pppp
#define ppppppppppppppppppppppppppppppppppppp {
#define ppppppppppp 1
#define ppppppppppppppppppppppppppppppppppppppppppppppp 'p'
#define pppppppppppppppppp 2
#define ppppppppppppppppppppppppppppppp 7
#define pppppppppppppppppppppppppppppppppppppppppppppppppppp "%20s"
#define pppppppppppppppppppppppppppppppppppppppppp 11
#define ppppppppppppppppppppppppppp }
#define ppppppppppppppppppppp return
#define pppppppppppppppppppppppppppp '?'
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppp 20
#define ppppppppppppppppppppppppppppppppppppppppp ' '
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 5
#define pppppppppppppppppppppppppppppp 0x20
#define ppppppppppppppppppppppppppppppppppppppppppppppppppp 'e'
#define pppppppppppppppppppppppppppppppp "Correct!\n"
#define ppppppppppppppppppppppppppppp char
#define pppppppppp 0
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 15
#define ppppppppppppppppppppppppppppppppppppppp else
#define pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp 14
#define pppppppppppppppppppppp '{'
#define ppppppppppppppppppppppppppppppppppppppppppppppppppppp if
#define pppppppppppppp ,
#define ppppppppppppppppppppppppppppppppppp 'p'
#define ppppppppppppppppppppppppppppppppp "Incorrect!\n"
#define ppppp ==
#define pppppppppppppppppppppppppppppppppppppppppppppppppp '1'
#define pppppppppppppppppppppppppppppppppppppppppppppp 3

#include <stdio.h>
#include <stdlib.h>

ppp ppppppppppppppppppp ppppppppppppppppppppppppppppppppppppp ppppppppppppppppppppppppppppp pp[pppppppppppppppppppppppppppppp] ppppppppppppppppp ppppppppppppppppppppppppppppp pppppppppppppppppppppppppppppppppppppp[ppppppppppppppppppppppppppppppp] pppppppppppppppppppppppppppppppppppppppppppp ppppppppppppppppppppppppppppppppppppp ppppppppppppppppppppppppppppppppppppppppppp pppppppppppppp ppppppppppppppp pppppppppppppp pppppp pppppppppppppp pppppppppppppppppppppppppppppppppppppppp pppppppppppppp pppppppppppppppppppppppppppp pppppppppppppp ppppppppppppppppppppppppppppppppppppppppp pppppppppppppp ppppppppppppppppppppppppp ppppppppppppppppppppppppppp ppppppppppppppppp pppppppppppppppppppppppppppppppppppp(pppppppppppppppppppppppppppppppppppppp)
ppppppppppppppppp pppppppppppppppppppppppppppppppppppppppppppppppp(pppppppppppppppppppppppppppppppppppppppppppppppppppp pppppppppppppp p) ppppppppppppppppp ppppppppppppppppppppppppppppppppppppppppppppppppppppp(pp[pppppppppppp] ppppp pppppppppppppppppppppp ppppppppp pp[pppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[pppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppp pppp pp[pppppppppppppppppppppppppppppppppp] ppppp pppppppp pppp pp[pppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp pppppppppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[ppppppppppp] ppppp ppppppppppppppp ppppppppp pp[pppppppppppppppppp] ppppp pppppp pppp pp[pppppppppppppppp] ppppp pppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[ppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppppp pppp pp[pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp pppppppp ppppppppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppp ppppppppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp pppppppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[pppppppppppppppppppppppppppppppppppppppppp] ppppp pppppppppppppppppppp pppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppp ppppppppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppppppppppp pppp pp[pppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppp pppp pp[ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppp pppp pp[pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp] ppppp ppppppppppppp pppp pp[ppppppppppppppppppppppppppppppp] ppppp ppppppppppppppppppppppppppppppppppppppppppppppp) ppppppppppppppppppppppppppppppppppppp pppppppppppppppppppppppppppppppppppp(pppppppppppppppppppppppppppppppp)
ppppppppppppppppp ppppppppppppppppppppppppppp ppppppppppppppppppppppppppppppppppppppp ppppppppppppppppppppppppppppppppppppp pppppppppppppppppppppppppppppppppppp(ppppppppppppppppppppppppppppppppp)
ppppppppppppppppp ppppppppppppppppppppppppppp ppppppppppppppppppppp pppppppppp ppppppppppppppppp ppppppppppppppppppppppppppp
